export const uiContent = {
  commandPalette: {
    triggerLabel: 'Open command palette',
    shortcutLabel: 'Ctrl K',
    searchLabel: 'Search portfolio',
    searchPlaceholder: 'Projects, resume, contact...',
    projectPrefix: 'Project:',
  },
  projectCard: {
    detailsAriaPrefix: 'Open',
    detailsAriaSuffix: 'details',
    screenshotSuffix: 'screenshot',
    caseStudyLabel: 'Case Study',
    liveDemoLabel: 'Live Demo',
    githubLabel: 'GitHub',
    techSeparator: ' / ',
  },
  projectDetails: {
    backLabel: 'Back to projects',
    liveDemoLabel: 'Live Demo',
    githubLabel: 'GitHub',
    mainScreenshotSuffix: 'main screenshot',
    screenshotLabel: 'screenshot',
    detailCards: [
      { label: 'Overview', field: 'desc', type: 'text' },
      { label: 'Problem', field: 'problem', type: 'text' },
      { label: 'Solution', field: 'solution', type: 'text' },
      { label: 'Challenges', field: 'challenges', type: 'list' },
      { label: 'Lessons Learned', field: 'lessons', type: 'list' },
    ],
    listSeparator: ', ',
    techStackTitle: 'Tech Stack',
    relatedProjectsTitle: 'Related Projects',
  },
}
