import {
  FaAws,
  FaBootstrap,
  FaCss3Alt,
  FaEnvelope,
  FaFigma,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJs,
  FaLinkedinIn,
  FaMicrosoft,
  FaNodeJs,
  FaPaintBrush,
  FaPalette,
  FaReact,
} from 'react-icons/fa'
import {
  FiBriefcase,
  FiGlobe,
  FiMapPin,
  FiUser,
} from 'react-icons/fi'
import {
  SiAngular,
  SiCloudflare,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGooglecloud,
  SiGraphql,
  SiJest,
  SiKubernetes,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNpm,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiRedis,
  SiRender,
  SiSass,
  SiSvelte,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVuedotjs,
} from 'react-icons/si'
import {
  VscCode,
} from 'react-icons/vsc'

export const iconRegistry = {
  user: FiUser,
  briefcase: FiBriefcase,
  mapPin: FiMapPin,
  globe: FiGlobe,
  email: FaEnvelope,
  linkedin: FaLinkedinIn,
  html: FaHtml5,
  css: FaCss3Alt,
  javascript: FaJs,
  typescript: SiTypescript,
  python: SiPython,
  java: SiOpenjdk,
  php: SiPhp,
  react: FaReact,
  angular: SiAngular,
  vue: SiVuedotjs,
  nextjs: SiNextdotjs,
  svelte: SiSvelte,
  tailwind: SiTailwindcss,
  bootstrap: FaBootstrap,
  sass: SiSass,
  node: FaNodeJs,
  express: SiExpress,
  nestjs: SiNestjs,
  graphql: SiGraphql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  redis: SiRedis,
  firebase: SiFirebase,
  jest: SiJest,
  aws: FaAws,
  azure: FaMicrosoft,
  googleCloud: SiGooglecloud,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  cloudflare: SiCloudflare,
  vercel: SiVercel,
  netlify: SiNetlify,
  render: SiRender,
  git: FaGitAlt,
  github: FaGithub,
  code: VscCode,
  npm: SiNpm,
  vite: SiVite,
  postman: SiPostman,
  figma: FaFigma,
  canva: FaPalette,
  paint: FaPaintBrush,
}

export function getIcon(icon) {
  return iconRegistry[icon] ?? FiUser
}
